# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  name: 'MyAgentPool1'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    #@jdkVersionOption: '11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    goals: 'package'

- task: CopyFiles@2
  inputs:
    Contents: '***'
    TargetFolder: :'$(build.artifactsstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactsstagingdirectory)'
    ArtifactName: drop
    publishLocation: 'Container'

- script: echo '$(Pipeline.Workspace)'
    